# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "master", "dev"  ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
   CI:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    
    - name: set-up node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        
    - name: clean install node package    
      run: npm ci
      
    - name: run test
      run: npm test
