# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD

on:
  push:
    branches: ['master', 'dev']
  pull_request:
    branches: ['master', 'dev']

jobs:
  CI:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: set-up node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: clean install node package
        run: npm ci

      - name: build
        run: npm run build

      - name: run test
        run: npm test

  CD:
    needs: CI
    runs-on: ubuntu-20.04

    steps:
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            export NODE_OPTIONS="--max-old-space-size=2048"
            cd thbnb
            cd TaeHyeongBnb
            git pull
            npm ci
            npm run build
            pm2 restart main
